# Generated by Django 5.1.5 on 2025-02-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_backend', '0003_rename_created_at_message_timestamp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='No bio available'),
        ),
    ]
